/**
 * 把 src/client/index.jsx 打成 DSH 客户端插件产物 lib/client.js。
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const HERE = fileURLToPath(new URL("..", import.meta.url));
const OUT = join(HERE, "lib/client.js");

export async function renderClientBundle() {
  const pkg = JSON.parse(await readFile(join(HERE, "package.json"), "utf8"));
  const result = await build({
    absWorkingDir: HERE,
    entryPoints: [join(HERE, "src", "client", "index.jsx")],
    bundle: true,
    write: false,
    format: "cjs",
    platform: "browser",
    target: ["es2022"],
    jsx: "transform",
    // 官方客户端包一律**外部化**（2026-09-28 加）：交给宿主的客户端模块表提供单例。
    // 打进来的后果是第二份实例 —— React 上下文/CSS 注入各一套，体积也翻倍。
    // 声明过的包由宿主保证「先于消费方到达」（见 package.json 的 dsh.client.inject）。
    external: ["react", "@deepseek-ai/*"],
    minify: false,
    sourcemap: false,
    legalComments: "none",
    logLevel: "warning",
  });
  const body = result.outputFiles[0].text.trimEnd();
  return [
    "// dsh-helper client bundle — generated by tools/build-client.mjs, do not edit.",
    "window.__ModuleLoader__.load({",
    `  id: ${JSON.stringify(pkg.name)},`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  }",
    "});",
    "",
  ].join("\n");
}

export async function writeClientBundle() {
  const envelope = await renderClientBundle();
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, envelope, "utf8");
  return Buffer.byteLength(envelope);
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  const size = await writeClientBundle();
  console.log(`已生成 ${OUT}（${size} 字节）`);
}
